# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cee9e6a0724953c43b13703d5c82adba33759a6989047fd9816cd9b7b9ca2d65e7682a4926bc6ad7434059529170076646a8070194d5402f7be5d194819690bc

test:
  secret_key_base: 54ca017fe15dd9f934108d1c899bd4cc49617347c0c48134414a1eace88f969093085cdbccb9243805c8a1f38480683a0f13c386ba0a22aaa4dee01d4d969f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
